version: '3'
services:
  golang:
    # image: golang:1.19.11-alpine
    image: golang:latest
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: "."
        target: "/go/src/app"
    tty: true
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
volumes:
  db-store: