version: '3'
services:
  golang:
    image: golang:latest
    ports:
      - 8080:80
    volumes:
      - ..:/workspace/golang
    tty: true
    depends_on:
      - db
    restart: always  
    init: true
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_TCP_PORT: 3306
      MYSQL_HOST: mysqlhost # 接続先dbのcontainer_nameと一致させる必要がある
      MYSQL_DATABASE: mvc
      MYSQL_USER: mvc
      MYSQL_PASSWORD: password
  db:
    image: mysql:latest
    container_name: mysqlhost
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - db:mysql
    ports:
        - 8888:80
    environment:
        PMA_HOST: mysql
volumes:
  db-store: